project 'microLoggerDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'microLoggerDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for microLoggerDemo
  pod 'microLogger', :git => 'https://github.com/micromanc3r/microLogger.git', :tag => '1.0.0'

end
