update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do
    scan(
      scheme: "MicroLogger",
      skip_build: false,
      skip_slack: true,
      clean: true
    )
  end
end
